# frozen_string_literal: true

module Candid
  module Commons
    module Types
      module FacilityTypeCode
        extend Candid::Internal::Types::Enum

        PHARMACY = "01"
        TELEHEALTH = "02"
        SCHOOL = "03"
        HOMELESS_SHELTER = "04"
        INDIAN_HEALTH_SERVICE_FREE_STANDING = "05"
        INDIAN_HEALTH_SERVICE_PROVIDER_BASED = "06"
        TRIBAL_FREE_STANDING = "07"
        TRIBAL_PROVIDER_BASED = "08"
        PRISON_OR_CORRECTIONAL_FACILITY = "09"
        TELEHEALTH_PATIENT_HOME = "10"
        OFFICE = "11"
        HOME = "12"
        ASSISTED_LIVING_FACILITY = "13"
        GROUP_HOME = "14"
        MOBILE_UNIT = "15"
        TEMPORARY_LODGING = "16"
        WALK_IN_RETAIL_HEALTH_CLINIC = "17"
        PLACE_OF_EMPLOYMENT_WORKSITE = "18"
        OFF_CAMPUS_OUTPATIENT_HOSPITAL = "19"
        URGENT_CARE_FACILITY = "20"
        INPATIENT_HOSPITAL = "21"
        OUTPATIENT_HOSPITAL = "22"
        EMERGENCY_ROOM_HOSPITAL = "23"
        AMBULATORY_SURGICAL_CENTER = "24"
        BIRTHING_CENTER = "25"
        MILITARY_TREATMENT_FACILITY = "26"
        SKILLED_NURSING_FACILITY = "31"
        NURSING_FACILITY = "32"
        CUSTODIAL_CARE_FACILITY = "33"
        HOSPICE = "34"
        AMBULANCE_LAND = "41"
        AMBULANCE_AIR_OR_WATER = "42"
        INDEPENDENT_CLINIC = "49"
        FEDERALLY_QUALIFIED_HEALTH_CENTER = "50"
        INPATIENT_PSYCHIATRIC_FACILITY = "51"
        PSYCHIATRIC_FACILITY_PARTIAL_HOSPITALIZATION = "52"
        COMMUNITY_MENTAL_HEALTH_CENTER = "53"
        INTERMEDIATE_CARE_FACILITY_MENTALLY_RETARDED = "54"
        RESIDENTIAL_SUBSTANCE_ABUSE_TREATMENT_FACILITY = "55"
        PSYCHIATRIC_RESIDENTIAL_TREATMENT_CENTER = "56"
        NON_RESIDENTIAL_SUBSTANCE_ABUSE_TREATMENT_FACILITY = "57"
        NON_RESIDENTIAL_OPIOID_TREATMENT_FACILITY = "58"
        MASS_IMMUNIZATION_CENTER = "60"
        COMPREHENSIVE_INPATIENT_REHABILITATION_FACILITY = "61"
        COMPREHENSIVE_OUTPATIENT_REHABILITATION_FACILITY = "62"
        END_STAGE_RENAL_DISEASE_TREATMENT_FACILITY = "65"
        STATE_OR_LOCAL_PUBLIC_HEALTH_CLINIC = "71"
        RURAL_HEALTH_CLINIC = "72"
        INDEPENDENT_LABORATORY = "81"
        OTHER_UNLISTED_FACILITY = "99"
      end
    end
  end
end
