# frozen_string_literal: true

module Candid
  module Commons
    module Types
      module RejectionReason
        extend Candid::Internal::Types::Enum

        DUPLICATE_CLAIM = "DUPLICATE_CLAIM"
        EXCEEDS_TIMELY_FILING = "EXCEEDS_TIMELY_FILING"
        INVALID_OR_MISSING_MODIFIER = "INVALID_OR_MISSING_MODIFIER"
        INVALID_OR_MISSING_DIAGNOSIS_CODE = "INVALID_OR_MISSING_DIAGNOSIS_CODE"
        INVALID_OR_MISSING_PLACE_OF_SERVICE = "INVALID_OR_MISSING_PLACE_OF_SERVICE"
        INVALID_OR_MISSING_PROCEDURE_CODE = "INVALID_OR_MISSING_PROCEDURE_CODE"
        INVALID_OR_MISSING_NDC = "INVALID_OR_MISSING_NDC"
        INVALID_OR_MISSING_DATE_OF_SERVICE = "INVALID_OR_MISSING_DATE_OF_SERVICE"
        OTHER_INVALID_CLAIM_OR_SERVICE_LINE_INFORMATION = "OTHER_INVALID_CLAIM_OR_SERVICE_LINE_INFORMATION"
        MULTIPLE_CODING_ISSUES = "MULTIPLE_CODING_ISSUES"
        INCORRECT_OR_MISSING_INSURANCE_INFORMATION = "INCORRECT_OR_MISSING_INSURANCE_INFORMATION"
        INCORRECT_OR_MISSING_PATIENT_DEMOGRAPHIC = "INCORRECT_OR_MISSING_PATIENT_DEMOGRAPHIC"
        NO_ACTIVE_COVERAGE = "NO_ACTIVE_COVERAGE"
        COORDINATION_OF_BENEFITS = "COORDINATION_OF_BENEFITS"
        OTHER_PATIENT_INFORMATION = "OTHER_PATIENT_INFORMATION"
        INCORRECT_PAYER = "INCORRECT_PAYER"
        MISSING_PAYER_ADDRESS = "MISSING_PAYER_ADDRESS"
        OTHER_PAYER_INFORMATION = "OTHER_PAYER_INFORMATION"
        INCORRECT_OR_MISSING_TAXONOMY_CODE = "INCORRECT_OR_MISSING_TAXONOMY_CODE"
        INCORRECT_OR_MISSING_NATIONAL_PROVIDER_IDENTIFIER = "INCORRECT_OR_MISSING_NATIONAL_PROVIDER_IDENTIFIER"
        NO_EFFECTIVE_ENROLLMENT = "NO_EFFECTIVE_ENROLLMENT"
        OTHER_PROVIDER_INFORMATION = "OTHER_PROVIDER_INFORMATION"
        ADMIT_OR_DISCHARGE_DATE = "ADMIT_OR_DISCHARGE_DATE"
        DOI_OR_DATE_OF_ONSET = "DOI_OR_DATE_OF_ONSET"
        OTHER_DRUG_RELATED = "OTHER_DRUG_RELATED"
        COB_INFORMATION = "COB_INFORMATION"
        QUANTITY_OR_UNITS = "QUANTITY_OR_UNITS"
        CPT_DESCRIPTION = "CPT_DESCRIPTION"
        INVALID_CORRECTED_OR_VOIDED_CLAIM = "INVALID_CORRECTED_OR_VOIDED_CLAIM"
        INCORRECT_OR_INVALID_MEMBER_ID = "INCORRECT_OR_INVALID_MEMBER_ID"
        INCORRECT_PATIENT_OR_SUBSCRIBER_DOB = "INCORRECT_PATIENT_OR_SUBSCRIBER_DOB"
        INCORRECT_PATIENT_OR_SUBSCRIBER_GENDER = "INCORRECT_PATIENT_OR_SUBSCRIBER_GENDER"
        INCORRECT_PATIENT_OR_SUBSCRIBER_ADDRESS = "INCORRECT_PATIENT_OR_SUBSCRIBER_ADDRESS"
        INCORRECT_PATIENT_OR_SUBSCRIBER_NAME = "INCORRECT_PATIENT_OR_SUBSCRIBER_NAME"
        INCORRECT_INSURANCE_PLAN_TYPE = "INCORRECT_INSURANCE_PLAN_TYPE"
        INCORRECT_INSURANCE_TYPE = "INCORRECT_INSURANCE_TYPE"
        INVALID_PAYER_ID = "INVALID_PAYER_ID"
        SERVICE_FACILITY = "SERVICE_FACILITY"
        CLIA = "CLIA"
        INCORRECT_OR_MISSING_OTHER_PROVIDER_TAXONOMY = "INCORRECT_OR_MISSING_OTHER_PROVIDER_TAXONOMY"
        INCORRECT_OR_MISSING_RENDERING_TAXONOMY = "INCORRECT_OR_MISSING_RENDERING_TAXONOMY"
        INCORRECT_OR_MISSING_BILLING_TAXONOMY = "INCORRECT_OR_MISSING_BILLING_TAXONOMY"
        INCORRECT_OR_MISSING_OTHER_PROVIDER_NPI = "INCORRECT_OR_MISSING_OTHER_PROVIDER_NPI"
        INCORRECT_OR_MISSING_RENDERING_NPI = "INCORRECT_OR_MISSING_RENDERING_NPI"
        INCORRECT_OR_MISSING_BILLING_NPI = "INCORRECT_OR_MISSING_BILLING_NPI"
        INCORRECT_OR_INVALID_TIN = "INCORRECT_OR_INVALID_TIN"
        INCORRECT_OR_MISSING_OTHER_PROVIDER_ID = "INCORRECT_OR_MISSING_OTHER_PROVIDER_ID"
        INCORRECT_OR_MISSING_PROVIDER_ADDRESS = "INCORRECT_OR_MISSING_PROVIDER_ADDRESS"
        UNKNOWN = "UNKNOWN"
      end
    end
  end
end
