# frozen_string_literal: true

module Candid
  module Commons
    module Types
      module ReportTypeCode
        extend Candid::Internal::Types::Enum

        C_03 = "03"
        C_04 = "04"
        C_05 = "05"
        C_06 = "06"
        C_07 = "07"
        C_08 = "08"
        C_09 = "09"
        C_10 = "10"
        C_11 = "11"
        C_13 = "13"
        C_15 = "15"
        C_21 = "21"
        CA_3 = "A3"
        CA_4 = "A4"
        CAM = "AM"
        CAS = "AS"
        CB_2 = "B2"
        CB_3 = "B3"
        CB_4 = "B4"
        CBR = "BR"
        CBS = "BS"
        CBT = "BT"
        CCB = "CB"
        CCK = "CK"
        CCT = "CT"
        CD_2 = "D2"
        CDA = "DA"
        CDB = "DB"
        CDG = "DG"
        CDJ = "DJ"
        CDS = "DS"
        CEB = "EB"
        CHC = "HC"
        CHR = "HR"
        CI_5 = "I5"
        CIR = "IR"
        CLA = "LA"
        CM_1 = "M1"
        CMT = "MT"
        CNN = "NN"
        COB = "OB"
        COC = "OC"
        COD = "OD"
        COE = "OE"
        COX = "OX"
        COZ = "OZ"
        CP_4 = "P4"
        CP_5 = "P5"
        CPE = "PE"
        CPN = "PN"
        CPO = "PO"
        CPQ = "PQ"
        CPY = "PY"
        CPZ = "PZ"
        CRB = "RB"
        CRR = "RR"
        CRT = "RT"
        CRX = "RX"
        CSG = "SG"
        CV_5 = "V5"
        CXP = "XP"
      end
    end
  end
end
