# frozen_string_literal: true

module Candid
  module Commons
    module Types
      module State
        extend Candid::Internal::Types::Enum
        AA = "AA"
        AE = "AE"
        AP = "AP"
        AL = "AL"
        AK = "AK"
        AS = "AS"
        AZ = "AZ"
        AR = "AR"
        CA = "CA"
        CO = "CO"
        CT = "CT"
        DC = "DC"
        DE = "DE"
        FL = "FL"
        FM = "FM"
        GA = "GA"
        GU = "GU"
        HI = "HI"
        ID = "ID"
        IL = "IL"
        IN = "IN"
        IA = "IA"
        KS = "KS"
        KY = "KY"
        LA = "LA"
        ME = "ME"
        MD = "MD"
        MA = "MA"
        MH = "MH"
        MI = "MI"
        MN = "MN"
        MP = "MP"
        MS = "MS"
        MO = "MO"
        MT = "MT"
        NE = "NE"
        NV = "NV"
        NH = "NH"
        NJ = "NJ"
        NM = "NM"
        NY = "NY"
        NC = "NC"
        ND = "ND"
        OH = "OH"
        OK = "OK"
        OR = "OR"
        PA = "PA"
        PR = "PR"
        PW = "PW"
        RI = "RI"
        SC = "SC"
        SD = "SD"
        TN = "TN"
        TX = "TX"
        UT = "UT"
        VI = "VI"
        VT = "VT"
        VA = "VA"
        WA = "WA"
        WV = "WV"
        WI = "WI"
        WY = "WY"end
    end
  end
end
