# frozen_string_literal: true

module Candid
  module Tasks
    module Commons
      module Types
        module TaskType
          extend Candid::Internal::Types::Enum

          CUSTOMER_DATA_REQUEST = "CUSTOMER_DATA_REQUEST"
          CLAIM_SUBMISSION_RUN_VALIDATIONS_FAILURE = "CLAIM_SUBMISSION_RUN_VALIDATIONS_FAILURE"
          CLAIM_SUBMISSION_SUBMIT_CLAIM_FAILURE = "CLAIM_SUBMISSION_SUBMIT_CLAIM_FAILURE"
          CLAIM_SUBMISSION_TRANSFORM_FAILURE = "CLAIM_SUBMISSION_TRANSFORM_FAILURE"
          CODE_CLAIM = "CODE_CLAIM"
          CODE_CLAIM_REVIEW = "CODE_CLAIM_REVIEW"
          ELIGIBILITY = "ELIGIBILITY"
          CLAIM_FOLLOW_UP = "CLAIM_FOLLOW_UP"
          REJECTION_RESOLUTION = "REJECTION_RESOLUTION"
          PAYER_CONFIGURATION_ERROR = "PAYER_CONFIGURATION_ERROR"
          DENIAL_RESOLUTION = "DENIAL_RESOLUTION"
          MISSING_ENROLLMENT = "MISSING_ENROLLMENT"
          CHARGE_CAPTURE_UPDATE = "CHARGE_CAPTURE_UPDATE"
        end
      end
    end
  end
end
