# frozen_string_literal: true

module Candid
  module WriteOffs
    module V1
      module Types
        module InsuranceWriteOffReason
          extend Candid::Internal::Types::Enum
          SMALL_BALANCE = "SMALL_BALANCE"
          NO_AUTHORIZATION_REFERRAL = "NO_AUTHORIZATION_REFERRAL"
          TIMELY_FILING = "TIMELY_FILING"
          STALE_DATE = "STALE_DATE"
          TIMELY_FILING_LATE_ENCOUNTER = "TIMELY_FILING_LATE_ENCOUNTER"
          CREDENTIALING_OR_CONTRACTING = "CREDENTIALING_OR_CONTRACTING"
          NON_COVERED_MAX_BENEFIT = "NON_COVERED_MAX_BENEFIT"
          NOT_MEDICALLY_NECESSARY = "NOT_MEDICALLY_NECESSARY"
          BUNDLED_OR_INCLUSIVE = "BUNDLED_OR_INCLUSIVE"
          UNCOLLECTIBLE_OR_NON_BILLABLE = "UNCOLLECTIBLE_OR_NON_BILLABLE"
          EFFORTS_EXHAUSTED = "EFFORTS_EXHAUSTED"
          ADMINISTRATIVE_WRITE_OFF = "ADMINISTRATIVE_WRITE_OFF"
          CASE_RATE_OR_CAPITATED = "CASE_RATE_OR_CAPITATED"
          OTHER = "OTHER"
          UNKNOWN = "UNKNOWN"
          CONTRACTUAL_ADJUSTMENT = "CONTRACTUAL_ADJUSTMENT"
          PRIMARY_PAID_MAX_BENEFITS = "PRIMARY_PAID_MAX_BENEFITS"end
      end
    end
  end
end
