# frozen_string_literal: true

module CandidApiClient
  module OrganizationProviders
    module V2
      module Types
        class LicenseType
          MD = "MD"
          NP = "NP"
          PA = "PA"
          LMFT = "LMFT"
          LCPC = "LCPC"
          LCSW = "LCSW"
          PMHNP = "PMHNP"
          FNP = "FNP"
          LPCC = "LPCC"
          DO = "DO"
          RD = "RD"
          SLP = "SLP"
          APRN = "APRN"
          LPC = "LPC"
          PHD = "PHD"
          PSYD = "PSYD"
          LMSW = "LMSW"
          LMHC = "LMHC"
          OTHER_MASTERS = "OTHER_MASTERS"
          BCBA = "BCBA"
          UNKNOWN = "UNKNOWN"
          RPH = "RPH"
          PHT = "PHT"
          LAC = "LAC"
          LMT = "LMT"
          DC = "DC"
          ND = "ND"
          MA = "MA"
          PT = "PT"
          IBCLC = "IBCLC"
          RN = "RN"
          DPT = "DPT"
          LCMHC = "LCMHC"
          CNM = "CNM"
          RNFA = "RNFA"
          ACSW = "ACSW"
          APC = "APC"
          BCABA = "BCABA"
          BHA = "BHA"
          OD = "OD"
          DPM = "DPM"
          DA = "DA"
          DDS = "DDS"
          DEH = "DEH"
          DMD = "DMD"
          PTA = "PTA"
          LCADC = "LCADC"
          LCAT = "LCAT"
          LCMHCS = "LCMHCS"
          LCMHCA = "LCMHCA"
          LCSWA = "LCSWA"
          LICSW = "LICSW"
          LISW = "LISW"
          LMFTS = "LMFTS"
          LMFTA = "LMFTA"
          LPCI = "LPCI"
          LSCSW = "LSCSW"
          MHCA = "MHCA"
          MHT = "MHT"
          RBT = "RBT"
          RCSWI = "RCSWI"
          RHMCI = "RHMCI"
          LPN = "LPN"
          OTD = "OTD"
          OMS = "OMS"
          MFTA = "MFTA"
          APCC = "APCC"
          DNP = "DNP"
          AGNPBC = "AGNPBC"
          ANP = "ANP"
          FNPPP = "FNPPP"
          LCSWR = "LCSWR"
          ALC = "ALC"
          RMFTI = "RMFTI"
          LAMFT = "LAMFT"
          LPCA = "LPCA"
          LSWI = "LSWI"
          CSW = "CSW"
          CPC = "CPC"
          LGMFT = "LGMFT"
          LLPC = "LLPC"
          PLPC = "PLPC"
          PLMFT = "PLMFT"
          LMHCA = "LMHCA"
          CIT = "CIT"
          CT = "CT"
          MFT = "MFT"
          LSW = "LSW"
          PLMHP = "PLMHP"
          PCMSW = "PCMSW"
          LMHP = "LMHP"
          OTRL = "OTR/L"
          RPA = "RPA"
          COTA = "COTA"
          CRNP = "CRNP"
          SLP_CF = "SLP-CF"
          NP_C = "NP-C"
          PA_C = "PA-C"
          AMFT = "AMFT"
          CDN = "CDN"
          CNS = "CNS"
          MDPHD = "MDPHD"
          AUD = "AuD"
        end
      end
    end
  end
end
