# frozen_string_literal: true

module CandidApiClient
  module OrganizationProviders
    module V2
      module Types
        class LicenseType
          MD = "MD"
          NP = "NP"
          PA = "PA"
          LMFT = "LMFT"
          LCPC = "LCPC"
          LCSW = "LCSW"
          PMHNP = "PMHNP"
          FNP = "FNP"
          LPCC = "LPCC"
          DO = "DO"
          RD = "RD"
          SLP = "SLP"
          APRN = "APRN"
          LPC = "LPC"
          PHD = "PHD"
          PSYD = "PSYD"
          LMSW = "LMSW"
          LMHC = "LMHC"
          OTHER_MASTERS = "OTHER_MASTERS"
          BCBA = "BCBA"
          UNKNOWN = "UNKNOWN"
          RPH = "RPH"
          PHT = "PHT"
          LAC = "LAC"
          LMT = "LMT"
          DC = "DC"
          ND = "ND"
          MA = "MA"
          PT = "PT"
          IBCLC = "IBCLC"
          RN = "RN"
          DPT = "DPT"
          LCMHC = "LCMHC"
          CNM = "CNM"
          RNFA = "RNFA"
          ACSW = "ACSW"
          APC = "APC"
          BCABA = "BCABA"
          BHA = "BHA"
          OD = "OD"
          DPM = "DPM"
          DA = "DA"
          DDS = "DDS"
          DEH = "DEH"
          DMD = "DMD"
          PTA = "PTA"
          LCADC = "LCADC"
          LCAT = "LCAT"
          LCMHCS = "LCMHCS"
          LCMHCA = "LCMHCA"
          LCSWA = "LCSWA"
          LICSW = "LICSW"
          LISW = "LISW"
          LMFTS = "LMFTS"
          LMFTA = "LMFTA"
          LPCI = "LPCI"
          LSCSW = "LSCSW"
          MHCA = "MHCA"
          MHT = "MHT"
          RBT = "RBT"
          RCSWI = "RCSWI"
          RHMCI = "RHMCI"
          LPN = "LPN"
          OTD = "OTD"
          OMS = "OMS"
          MFTA = "MFTA"
          APCC = "APCC"
          DNP = "DNP"
        end
      end
    end
  end
end
