name: Publish
on: push
jobs:
  delete_test_tag:
    if: github.event_name == 'push' && github.ref == 'refs/tags/0.0.0'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Delete tag and release
        run: |
          git push --delete origin 0.0.0
          gh release delete 0.0.0 --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  publish:
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && github.ref != 'refs/tags/0.0.0'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

        - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
          with:
            ruby-version: 2.7
            bundler-cache: true

        - name: Test gem
          run: bundle install && bundle exec rake test
            
        - name: Build and Push Gem
          env:
            GEM_HOST_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
          run: |
            gem build candidhealth.gemspec

            gem push candidhealth-*.gem --host https://rubygems.org/
