name: Publish

on: [push]
jobs:
    publish:
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

          - uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
            with:
              ruby-version: 3.4 # gemspec requires >=3.3.0
              bundler-cache: true

          - name: Test gem
            run: bundle install && bundle exec rake test
              
          - name: Build and Push Gem
            env:
              GEM_HOST_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
            run: |
              gem build candidhealth.gemspec

              gem push candidhealth-*.gem --host https://rubygems.org/
    alert-on-failure:
      needs: [
        publish,
      ]
      if: ${{ !cancelled() && failure() }}
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          sparse-checkout: .github
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 #v3.9.1
        with:
          node-version: '16'
      - name: Install dependencies for PagerDuty action
        run: |
          cd .github/actions/pagerduty-alert
          npm install
      - name: Send PagerDuty Alert
        uses: ./.github/actions/pagerduty-alert
        id: pagerduty-alert
        with:
          pagerduty-api-key: "${{ secrets.PAGERDUTY_API_KEY }}"
          pagerduty-service-id:  "${{ secrets.PAGERDUTY_SERVICE_ID }}"
          pagerduty-user-id: "${{ secrets.PAGERDUTY_USER_ID }}"
          pagerduty-user-email: "${{ secrets.PAGERDUTY_USER_EMAIL }}"