name: Publish

on: [push]
jobs:
    publish:
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

          - uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f # v1
            with:
              ruby-version: 2.7
              bundler-cache: true

          - name: Test gem
            run: bundle install && bundle exec rake test
              
          - name: Build and Push Gem
            env:
              GEM_HOST_API_KEY: ${{ secrets.RUBY_GEMS_API_KEY }}
            run: |
              gem build candidhealth.gemspec

              gem push candidhealth-*.gem --host https://rubygems.org/
