# frozen_string_literal: true

module CandidApiClient
  module Commons
    module Types
      # Code identifying the type of insurance policy within a specific insurance
      #  program (X12 008020 Element 1336)
      class InsuranceTypeCode
        C_01 = "01"
        C_12 = "12"
        C_13 = "13"
        C_14 = "14"
        C_15 = "15"
        C_16 = "16"
        C_17 = "17"
        C_18 = "18"
        C_19 = "19"
        C_41 = "41"
        C_42 = "42"
        C_43 = "43"
        C_47 = "47"
        CAP = "AP"
        CC_1 = "C1"
        CCO = "CO"
        CCP = "CP"
        CD = "D"
        CDB = "DB"
        CE = "E"
        CEP = "EP"
        CFF = "FF"
        CGP = "GP"
        CHA = "HA"
        CHB = "HB"
        CHD = "HD"
        CHG = "HG"
        CHM = "HM"
        CHN = "HN"
        CHP = "HP"
        CHS = "HS"
        CIN = "IN"
        CIP = "IP"
        CLC = "LC"
        CLD = "LD"
        CLI = "LI"
        CLT = "LT"
        CM = "M"
        CMA = "MA"
        CMB = "MB"
        CMC = "MC"
        CMD = "MD"
        CME = "ME"
        CMF = "MF"
        CMH = "MH"
        CMI = "MI"
        CMJ = "MJ"
        CMK = "MK"
        CML = "ML"
        CMM = "MM"
        CMN = "MN"
        CMO = "MO"
        CMP = "MP"
        CMR = "MR"
        CMT = "MT"
        CMV = "MV"
        COA = "OA"
        COT = "OT"
        CPE = "PE"
        CPL = "PL"
        CPP = "PP"
        CPR = "PR"
        CPS = "PS"
        CQM = "QM"
        CRP = "RP"
        CSP = "SP"
        CTF = "TF"
        CU = "U"
        CWC = "WC"
        CWU = "WU"
      end
    end
  end
end
